### ISSUE TITLE
can't read values back from DynamoDB

### ISSUE THREAD

**Issue by WillCodeForEver** [KayLerch/alexa-skills-kit-states-java#4]
I am running into the same issue...
I can persist user scoped model fine but cannot read it back..even if I hard code the id as a constant i.e. "bob" when writing and then reading the model back...

`	public static void persistState(Session session) {
		// take care of state
		try {
			String userId = session.getUser().getUserId();
			//AWSDynamoStateHandler can't handle IDs with "." convert them to "-"
			userId = userId.replaceAll("\\.", "-");
			logger.info("persistState() persisting state for user: " + userId);

			final AlexaStateHandler handler = new AWSDynamoStateHandler(session);
                         AlexaUser activeUser = handler.readModel(AlexaUser.class, "bob")
						.orElse(handler.createModel(AlexaUser.class, "bob"));
                                  ........
				activeUser.saveState();

			}
		} catch (AlexaStateException ase) {
			logger.error("Exception attempting to persist user data to dynamoDB ", ase);
		}
	}`

(i've confirmed that the data is written to DyanmoDB:

I see: 
amazon-user-id
model-class : 
state: "id" : "bob" 
)

reading the value back with id "bob" doesn't load the model ...

`	public static Optional<AlexaUser> restoreState(SpeechletRequestEnvelope<LaunchRequest> requestEnvelope) {

		Session session = requestEnvelope.getSession();
		String userId = session.getUser().getUserId();
		userId = userId.replaceAll("\\.", "-");
		logger.info("restoreState(): attempting to restore state for userId: " + userId);
		
		Optional<AlexaUser> activeUser = Optional.empty();
		try {
			final AlexaStateHandler handler = new AWSDynamoStateHandler(requestEnvelope.getSession());

			activeUser = handler.readModel(AlexaUser.class, "bob");
			if (activeUser.isPresent()) {
				logger.info(
						"restoreState() Found previous session for this user, restoring session attributes from AlexaUser: "
	                 .....//DO work here....
		} catch (AlexaStateException e) {
			logger.error("Exception while attempting to load user's saved search attributes from dynamoDB: " + userId, e);
		}
		return activeUser;
	}`

I've narrowed it down to where it short-circuits the readModel logic...i am not sure if this is a bug or not...

AWSDynamoStateHandler line# 251  readModel(...)  calls  getItems(..) and passes "false" as the 2nd argument:
`final List<Map<String, AttributeValue>> readRequests = getItems(model, false);`

getItems  then adds primary keys as attribute and only loads USER scoped attribute if "withState" is true..but 'false' was passed..so it returns an empty list..which cases readModel to log line # 265 and return an empty Optional....

**Comment by KayLerch** [comment]
Passing in "false" to getItems is not the issue as getItems is only used to generate the attribute-key-collection to let readItemsFromDb do the actual read from Dynamo. 

Does AlexaUser have members annotated as @AlexaStateSave(Scope = AlexaScope.USER)? I assume not as your payload in the Dynamo record does not contain any values except for the id. If there no user-scoped field in your model, getItems won't generate a readRequest (look at line 297 in AWSDynamoStateHandler). The logic behind is to avoid unnecessary reads from Dynamo if there's nothing to load into the model-class.

**Comment by KayLerch** [comment]
After spending some time on it I have to admit there was a bug in my code that should now be fixed. Please upgrade to v1.0.1

**Comment by WillCodeForEver** [comment]
thanks Kay, i'll get back to this soon..i had to switch to persisting individual attributes due to this bug...i am on to implementing different features but when i get back to persistence i'll try to switch to User model method and test it out.
thanks again for the research.
